services:
  db:
    image: postgres:16
    container_name: db_postgres
    env_file:
      - db-service/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network

  db_service:
    build: db-service
    container_name: db-service
    depends_on:
      - db
    env_file:
      - db-service/.env
    networks:
      - db_network
      - internal_network
    command: ["pdm", "run", "serve"]

  populate_whitelist:
    build: db-service
    container_name: populate_whitelist
    depends_on:
      - db
    env_file:
      - db-service/.env
    profiles:
      - optional
    networks:
      - db_network
    command: ["pdm", "run", "populate_whitelist"]
  
  administration_backend:
    build: administration-backend
    container_name: administration-backend
    depends_on:
      - db_service
    ports:
      - "8080:8000"
    networks:
      - internal_network
    command: ["pdm", "run", "serve"]

  execution_engine:
    build: execution-engine
    container_name: execution-engine
    depends_on:
      - db_service
      - redis
      - py-runner
    environment:
      - PY_RUNNER_URL=http://py-runner:8080/run 
    networks:
      - internal_network
    command: ["pdm", "run", "serve"]
    
  py-runner:
    build:
      context: ./services/py_runner
      dockerfile: Dockerfile
    user: "1000:1000"
    read_only: true
    tmpfs:
      - /tmp:size=64m,exec,nosuid,nodev
    pids_limit: 128
    mem_limit: 256m
    cpus: "1.0"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks: 
      - internal_network


  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - internal_network
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    env_file:
      - minio-service/.env
    volumes:
      - minio_data:/data
    networks:
      - internal_network
    ports:
      - "9000:9000"
      - "9001:9001"
    
volumes:
  pg_data:
  minio_data:

networks:
  db_network:
  internal_network:
