version: "3.9"
services:
  db:
    image: postgres:16
    container_name: db_postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: db-service
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "9000:8000"
    command: ["pdm", "run", "serve"]

  populate_whitelist:
    build: .
    container_name: populate_whitelist
    depends_on:
      - db
    env_file:
      - .env
    profiles:
      - optional
    command: ["pdm", "run", "populate_whitelist"]

volumes:
  pg_data:
